const img_loc_pub = '../src/assets/images/appartement-moderne-a-katowice-pologne-kast-design-img~d7a1430d0979a5ed_4-7861-1-1371fbc.jpg'
// const img_loc_pub = 'https://rayweblistapi.000webhostapp.com/assets/Afari_achat.c86baf17.png'

export let rent_objects = [
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    },
    {
    'tit' : 'appartement s+1 ',
    'dis' : 'appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz appartement s+1 meuble a la marsa au voisinage de jardin public sidi abd laziz',
    'img': `${img_loc_pub}`,
    'msg' : '',
    'price': '47000 TND',
    }
]